include:
  - project: '$CI_TEMPLATE'
    ref: master
    file: '.gitlab-ci-default.yaml'

###############################################################
# Build Stage
###############################################################

dev-pypi:
  extends: .dev-pypi

###############################################################
# Test Stage
###############################################################

test:
  stage: test
  tags:
    - stage-kube-newer
  image: public.ecr.aws/docker/library/python:3.10-slim-bullseye
  script:
    - pip install -q --upgrade pip
    - pip install -q pytest
    - pip install .
    - pytest -s -v

###############################################################
# Release Stage
###############################################################

release-pypi:
  extends: .release-pypi
  only:
    - master
