image: $REPO_URL/stage

stages:
  - build
  - test
  - release

default:
  before_script:
    - pip install -q --upgrade pip
    - pip install -q $END_TO_END_LIB@$CI_COMMIT_REF_NAME || pip install -q $END_TO_END_LIB
    - e2e init

###############################################################
# Build Stage (jobs inside a stage run in parallel)
###############################################################
dev-pypi:
  tags:
    - kube-small-new
  stage: build
  before_script:
    - pip3 install -q --upgrade pip setuptools twine wheel bump2version
  script:
    - SHORT_SHA=$(git rev-parse --short HEAD) bumpversion --no-commit --no-tag local
    - python setup.py -q bdist_wheel
    - twine upload --skip-existing --disable-progress-bar --non-interactive dist/*

###############################################################
# Test Stage
###############################################################
test-py310:
  tags:
    - kube-small-new
  image: $REPO_URL/public/docker/library/python:3.10-slim-bullseye
  stage: test
  before_script:
    - pip install -q --upgrade pip setuptools wheel
  script:
    - pip install .
    - pytest -s -v

###############################################################
# Release Stage
###############################################################
release-pypi:
  tags:
    - kube-small-new
  stage: release
  only:
    - master
  script:
    # release to internal pypi but do not tag yet
    - e2e release --skip-tag --remote https://github.com/polyswarm/$CI_PROJECT_NAME.git
