BLACK_FG = '\033[30m'
BLUE_FG = '\033[34m'
CYAN_FG = '\033[36m'
GREEN_FG = '\033[32m'
MAGENTA_FG = '\033[35m'
RED_FG = '\033[31m'
WHITE_FG = '\033[37m'
YELLOW_FG = '\033[33m'
RESET = '\033[0m'
UNDERLINE = '\033[4m'

GROUP_COLORS = {
    'NAME': UNDERLINE,
    'LABELS': YELLOW_FG,
    'ARCHIVES': BLACK_FG,
    'HEURISTICS': UNDERLINE,
    'MACROS': GREEN_FG,
    'LANGS': BLUE_FG,
    'OPERATING_SYSTEMS': CYAN_FG,
    'FAMILY': GREEN_FG,
    'VARIANT': WHITE_FG,
    'OBFUSCATION': BLACK_FG,
}
