
heuristics = [
    'heur[a-z]*',
    'gen(eric)?'
    'agent'
]

labels = {
  'adware': "Any software that is funded by advertising. Adware may also gather sensitive user information from a system.",
  'appender': { '__desc__': "File-infecting malware that places its code at the end of the files it infects, adjusting the file's entry point to cause its code to be executed before that in the original file."},
  'backdoor': "Malware which, once running on a system, opens a communication vector to the outside so the computer can be accessed remotely by an attacker.",
    'browser-modifier': {'__desc__': 'extension or plugin that modifies browser behavior',
                         '__alias__': ['bho']},
  'boot-sector-virus': "Malware that infects the master boot record of a storage device.",
  'bot': "Malware that resides on an infected system, communicating with and forming part of a botnet. The bot may be implanted by a worm or trojan, which opens a backdoor. The bot then monitors the backdoor for further instructions.",
  'cavity-filler': "A type of file-infecting virus that seeks unused space within the files it infects, inserting its code into these gaps to avoid changing the size of the file and thus not alerting integrity-checking software to its presence.",
  'clicker': { '__desc__': "A trojan that makes a system visit a specific web page, often very frequently and usually with the aim of increasing the traffic recorded by the site and thus increasing revenue from advertising. Clickers may also be used to carry out DDoS attacks.",
               '__alias__': ['trojan-clicker'] },
  'companion-virus': "A virus that takes the place of a particular file on a system instead of injecting code into it.",
  'data-diddler': "A type of malware that makes small, random changes to data, such as data in a spreadsheet, to render the data contained in a document inaccurate and in some cases worthless.",
  'ddos': { '__desc__': "A tool used to perform a distributed denial of service attack.",
            '__alias__': ['trojan-ddos', 'flooder', r'[a-z]+flooder'] },
  'downloader': "Malware programmed to download and execute other files, usually more complex malware.",
  'dropper': { '__desc__': "A type of Trojan that deposits an enclosed payload onto a destination host computer by loading itself into memory, extracting the malicious payload, and then writing it to the file system.",
               '__alias__': [ 'trojan-dropper' ] },
  'exploit-kit': "A software toolkit to target common vulnerabilities.",
  'file-infector-virus': "A virus that infects a system by inserting itself somewhere in existing files; this is the classic form of virus.",
  'file-less': "Malware that is file-less, i.e., executes through some other mechanism such as Powershell.",
  'fork-bomb': "A simple form of malware, a type of rabbit which launches more copies of itself. Once a fork bomb is executed, it will attempt to run several identical processes, which will do the same, the number growing exponentially until the system resources are overwhelmed by the number of identical processes running, which may in some cases bring the system down and cause a denial of service.",
  'greyware': { '__desc__': "Software that, while not definitely malicious, has a suspicious or potentially unwanted aspect.",
                '__alias__': ['hacktool', 'pua', 'joke', 'program', 'application', 'software-bundler', 'tool', 'virtool', 'misleading', 'settings-modifier', 'hoax', 'swbndlr', 'sftwrbndlr' ] },
  'implant': { '__desc__': "Code inserted into an existing program using a code patcher or other tool.",
               '__alias__': ['behavior'] },
  'keylogger': { '__desc__': "A type of program implanted on a system to monitor the keys pressed and thus record any sensitive data, such as passwords, entered by the user.",
                 '__alias__': ['monitoring-tool'] },
  'kleptographic-worm': "A worm that encrypts information assets on compromised systems so they can only be decrypted by the worm's author, also known as information-stealing worm.",
  'macro-virus': "A virus that uses a macro language, for example in Microsoft Office documents.",
  'malware-as-a-service': "Malware that is sold or produced as a service.",
    'test': { "__desc__": "A test file, not actually a virus", '__alias__': ['eicar', 'testfile']},
  'mass-mailer': { '__desc__': "A worm that uses email to propagate across the internet.",
                   '__alias__': ['spammer'] },
  'metamorphic-virus': "A virus that changes its own code with each infection.",
  'mid-infector': "A type of file-infecting virus which places its code in the middle of files it infects. It may move a section of the original code to the end of the file, or simply push the code aside to make space for its own code.",
  'mobile-code': "Either code received from remote, possibly untrusted systems, but executed on a local system; or software transferred between systems (e.g across a network) and executed on a local system without explicit installation or execution by the recipient.",
  'multipartite-virus': "Malware that infects boot records, boot sectors, and files.",
  'parental-control': { '__desc__': "A program that monitors or limits machine usage. Such programs can run undetected and can transmit monitoring information to another machine.",
                        '__alias__': ['monitoring-tool'] },
  'password-stealer': { '__desc__': "A type of trojan designed to steal passwords, personal data and details, or other sensitive information from an infected system.",
                        '__alias__': ['pws', 'trojanpws', 'stealer'] },
  'polymorphic-virus': { '__desc__': "A type of virus that encrypts its code differently with each infection (or with each generation of infections).",
                         '__alias__': ['packed', 'packer',
                                       # imported from clamav
                                       'parite', 'kriz', 'magistr', 'polipos',
                                       'md5sect', 'upx', 'fsg', 'swizzor',
                                       'petite', 'pespin', 'yc', 'wwpack',
                                       'nspack', 'mew', 'upack', 'aspack',
                                       'matchicon', 'imptbl'] },
  'premium-dialer-smser': "A type of malware whose primary aim is to dial (or send SMS messages to) premium rate numbers.",
  'prepender': "A file-infecting virus that inserts code at the beginning of the files it infects.",
  'ransomware': { '__desc__': "Malware that encrypts files on a victim's system, demanding payment of ransom in return for the access codes required to unlock files.",
                  '__alias__': ['ansom', 'ransom', 'trojan-ransom'] },
  'remote-access-trojan': { '__desc__': "A remote access trojan program (or RAT), is a trojan horse capable of controlling a machine through commands issued by a remote attacker.",
                            '__alias__': ['rat', 'remote-access'] },
  'resource-exploiter': { '__desc__': "A type of malware that steals a system's resources (e.g., CPU cycles), such as a bitcoin miner.",
                          '__alias__': ['zipbomb'] },
  'rogue-security-software': { '__desc__': "A fake security product that demands money to clean phony infections.",
                               '__alias__': ['rogue'] },
  'rootkit': "A method of hiding files or processes from normal methods of monitoring; often used by malware to conceal its presence and activities.",
  'scareware': "A program that reports false or significantly misleading information on the presence of security risks, threats, or system issues on the target computer.",
  'screen-capture': "A type of malware used to capture images from the target systems screen, used for exfiltration and command and control.",
  'security-assessment-tool': "A program that can be used to gather information for unauthorized access to computer systems.",
  'shellcode': { '__desc__': "Either a small piece of code that activates a command-line interface to a system that can be used to disable security measures, open a backdoor, or download further malicious code; or a small piece of code that opens a system up for exploitation, sometimes by not necessarily involving a command-line shell.",
                 '__alias__': ['exploit', 'exp'] },
  'spyware': "Software that gathers information and passes it to a third-party without adequate permission from the owner of the data. It may also refer to software that makes changes to a system or any of its component software, or which makes use of system resources without the full understanding and consent of the system owner.",
  'trackware': "Malware that traces a user's path on the Internet and sends information to third parties. Compare to spyware, which monitors system activity to capture confidential information such as passwords.",
  'trojan': { '__desc__': "Malware disguised as something inert or benign.",
              '__alias__': ['trojan(\s|_|-)?[a-z]+']},
  'virus': { '__desc__': "Self-replicating malware that requires human interaction to spread; also, self-replicating malware that runs and spreads by modifying and inserting itself into other programs or files.",
             '__alias__': ['spoofer', 'constructor'] },
  'web-bug': "Code embedded in a web page or email that checks whether a user has accessed the content (e.g., a tiny, transparent GIF image).",
  'worm': { '__desc__': "Self-replicating malware that propagates across a network either with or without human interaction.",
            '__alias__': ['i-worm', 'p2p-worm', 'im-worm', 'irc-worm', 'email-worm'] },
}
