#!/usr/bin/env python3
from contextlib import contextmanager
from pathlib import Path
import sys
import polyunite

try:
    from conftest import format_match, match_iter
except:
    sys.path.append(str(Path(__file__).parent.joinpath('../tests')))
    from conftest import format_match, match_iter

@contextmanager
def section(name):
    print("{:-^150}".format(name))
    yield lambda *a, **kw: print('  ', *a, **kw)

try:
    it = match_iter()
    while True:
        print(format_match(*next(it)))
except StopIteration as e:
    missing, errors = e.value

with section('MISSING') as pr:
    pr(missing)

with section('FAILURES') as pr:
    for engine, label, err in errors:
        pr("{:<15}: {:85} : {}".format(engine, label, err))

with section('INFO') as pr:
    pr('compile.cache_info: ', polyunite.vocab.VocabRegex.compile.cache_info())
