#!/usr/bin/env python3
import json
import os.path
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '../tests'))
from utils import match_iter  # noqa

print(
    json.dumps(
        [{
            'engine': vr.registration,
            'source': vr.source,
            'name': vr.name,
            'labels': list(vr.labels),
            'operating_system': vr.operating_system,
            'macro': vr.macro,
            'language': vr.language,
            'is_heuristic': vr.is_heuristic,
        } for vr in match_iter()],
        indent=2,
    )
)
