#!/usr/bin/env python3
import json
from pathlib import Path
import sys

try:
    from utils import match_iter
except:
    sys.path.append(str(Path(__file__).parent.joinpath('../tests')))
    from utils import match_iter


print(
    json.dumps(
        [{
            'engine': vr.registration,
            'source': vr.source,
            'name': vr.name,
            'labels': list(vr.labels),
            'operating_system': vr.operating_system,
            'macro': vr.macro,
            'language': vr.language,
            'is_heuristic': vr.is_heuristic,
        } for vr in match_iter()],
        indent=2,
    )
)
